services:
  postgres:
    image: postgres:16
    container_name: claims-api-postgres
    environment:
      POSTGRES_DB: claims_api_db
      POSTGRES_USER: claims_app
      POSTGRES_PASSWORD: claims_app_password
    ports:
      - "5433:5432"
    volumes:
      - claims_api_postgres_data_v4:/var/lib/postgresql/data

volumes:
  claims_api_postgres_data_v4: