spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/claims_db
    username: claims_user
    password: claims_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true