spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/claims_api_db
    username: claims_app
    password: claims_app_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true